import type { MenuItem } from './types';

export const initialMenuData: MenuItem[] = [
  {
    id: 'app-01',
    name: 'Bruschetta al Pomodoro',
    description: 'Toasted bread with fresh tomatoes, garlic, basil, and olive oil.',
    price: 8.50,
    category: 'Appetizers',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'bruschetta tomato',
    allergens: ['Gluten'],
  },
  {
    id: 'app-02',
    name: 'Calamari Fritti',
    description: 'Golden-fried squid rings served with a spicy marinara sauce.',
    price: 12.00,
    category: 'Appetizers',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'fried calamari',
  },
  {
    id: 'app-03',
    name: 'Caprese Salad',
    description: 'Fresh mozzarella, ripe tomatoes, basil, and a balsamic glaze.',
    price: 10.00,
    category: 'Appetizers',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'caprese salad',
    allergens: ['Dairy'],
  },
  {
    id: 'main-01',
    name: 'Spaghetti Carbonara',
    description: 'Classic pasta with pancetta, egg yolk, pecorino cheese, and black pepper.',
    price: 18.00,
    category: 'Main Courses',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'spaghetti carbonara',
    allergens: ['Gluten', 'Egg', 'Dairy'],
  },
  {
    id: 'main-02',
    name: 'Margherita Pizza',
    description: 'Traditional pizza with San Marzano tomatoes, fresh mozzarella, basil, and olive oil.',
    price: 16.50,
    category: 'Main Courses',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'margherita pizza',
    allergens: ['Gluten', 'Dairy'],
    extras: [
      { id: 'extra-1', name: 'Extra Mozzarella', price: 2.50 },
      { id: 'extra-2', name: 'Pepperoni', price: 3.00 },
      { id: 'extra-3', name: 'Mushrooms', price: 1.75 },
    ]
  },
  {
    id: 'main-03',
    name: 'Pollo alla Cacciatora',
    description: 'Braised chicken with onions, herbs, tomatoes, and bell peppers.',
    price: 22.00,
    category: 'Main Courses',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'chicken cacciatore',
  },
  {
    id: 'main-04',
    name: 'Bistecca alla Fiorentina',
    description: 'Thick-cut T-bone steak, grilled and seasoned with salt, pepper, and olive oil.',
    price: 45.00,
    category: 'Main Courses',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'florentine steak',
  },
  {
    id: 'dessert-01',
    name: 'Tiramisù',
    description: 'Coffee-soaked ladyfingers layered with a whipped mixture of eggs, sugar, and mascarpone cheese.',
    price: 9.00,
    category: 'Desserts',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'tiramisu dessert',
    allergens: ['Gluten', 'Egg', 'Dairy'],
  },
  {
    id: 'dessert-02',
    name: 'Panna Cotta',
    description: 'Silky smooth sweetened cream topped with a berry coulis.',
    price: 8.00,
    category: 'Desserts',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'panna cotta',
    allergens: ['Dairy'],
  },
  {
    id: 'drink-01',
    name: 'Mineral Water',
    description: 'Still or sparkling.',
    price: 3.00,
    category: 'Drinks',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'mineral water',
  },
  {
    id: 'drink-02',
    name: 'Espresso',
    description: 'A single shot of rich, intense coffee.',
    price: 2.50,
    category: 'Drinks',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'espresso coffee',
  },
];
